Feature/tri 488
catenax-ng/product-item-relationship-service pull request #109
Opened 2022-05-24 20:09 UTC by SaberIstos

2022-05-25 06:12 UTC, ds-jkreutzfeld commented on irs-models/src/main/java/net/catenax/irs/component/Jobs.java
> +@JsonIgnoreProperties(ignoreUnknown = true)
Why is this necessary?

2022-05-25 06:12 UTC, ds-jkreutzfeld commented on integration-tests/pom.xml
> +            <version>4.4.0</version>
Why do we need to downgrade?

2022-05-25 06:12 UTC, ds-jkreutzfeld commented on integration-tests/src/test/java/net/catenax/irs/smoketest/ItemGraphIntegrationTest.java
> +public class ItemGraphIntegrationTest {
Might as well call it a SmokeTest if it's in the smoketest package :)

2022-05-25 06:12 UTC, ds-jkreutzfeld commented on integration-tests/src/test/java/net/catenax/irs/smoketest/ItemGraphIntegrationTest.java
> +                                              .post("http://localhost:8081/irs/jobs")
Make this configurable so it can be executed against any environment

2022-05-25 06:12 UTC, ds-jkreutzfeld commented on integration-tests/src/test/java/net/catenax/irs/smoketest/ItemGraphIntegrationTest.java
> +        final Jobs responseGet = given().body(returnUncompletedJob)
I think "returnIncompleteJob" is a query parameter

2022-05-25 06:12 UTC, ds-jkreutzfeld commented on integration-tests/src/test/java/net/catenax/irs/smoketest/ItemGraphIntegrationTest.java
> +        TimeUnit.SECONDS.sleep(10);
Don't use a basic timeout here. It might be possible, that the job takes longer than 10 seconds or it might also finish in 2 seconds and the test will wait unnecessarily.
Instead, use tools like Awaitility to poll for the result until it succeeds or a timeout is reached.

2022-05-25 07:27 UTC, SaberIstos commented on irs-models/src/main/java/net/catenax/irs/component/Jobs.java
> +@JsonIgnoreProperties(ignoreUnknown = true)
It was added while investigating attempt. Removed.

2022-05-25 07:43 UTC, SaberIstos commented on integration-tests/src/test/java/net/catenax/irs/smoketest/ItemGraphIntegrationTest.java
> +public class ItemGraphIntegrationTest {
Refactored to public class ItemGraphSmokeTest

2022-05-25 07:50 UTC, SaberIstos commented on integration-tests/src/test/java/net/catenax/irs/smoketest/ItemGraphIntegrationTest.java
> +        final Jobs responseGet = given().body(returnUncompletedJob)
yes indeed. Handled as a query parameter --> send a request using Query Parameters in Rest Assured:
given().queryParam("returnUncompletedJob", true)

2022-05-25 09:01 UTC, SaberIstos commented on integration-tests/pom.xml
> +            <version>4.4.0</version>
As mentioned in the commit, I got the following error: 
java.lang.ExceptionInInitializerError
	at org.codehaus.groovy.reflection.ClassInfo.isValidWeakMetaClass(ClassInfo.java:283)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClassForClass(ClassInfo.java:253)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:309)
	at io.restassured.authentication.NoAuthScheme.$getStaticMetaClass(NoAuthScheme.groovy)
	at io.restassured.authentication.NoAuthScheme.<init>(NoAuthScheme.groovy)
	at io.restassured.RestAssured.<clinit>(RestAssured.java:355)
	at net.catenax.irs.smoketest.ItemGraphSmokeTest.testRegisterItemJob(ItemGraphSmokeTest.java:120)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: groovy.lang.GroovyRuntimeException: Conflicting module versions. Module [groovy-xml is loaded in versi [...]

2022-05-27 07:46 UTC, SaberIstos commented on integration-tests/src/test/java/net/catenax/irs/smoketest/ItemGraphIntegrationTest.java
> +        TimeUnit.SECONDS.sleep(10);
Changed to:
        // Integration test Scenario 2 STEP 3
        final Response responseGetPoll = given().queryParam("returnUncompletedJob", true)
                                                .get("http://localhost:8081/irs/jobs/" + jobId);

        await().atMost(10, TimeUnit.SECONDS)
               .until(() -> responseGetPoll.as(Jobs.class).getJob().getJobState().equals(JobState.COMPLETED));

        final Jobs jobs = responseGetPoll.then()
                                         .assertThat()
                                         .statusCode(HttpStatus.OK.value())
                                         .extract()
                                         .as(Jobs.class);

2022-05-31 07:28 UTC, ds-jkreutzfeld submitted a review, later dismissed

2022-05-31 07:28 UTC, ds-jkreutzfeld commented on integration-tests/src/test/java/net/catenax/irs/smoketest/ItemGraphSmokeTest.java
> +        final JobHandle responsePost = given().spec(requestSpecification)
There might be an easier way to pass the token:
.auth().oauth2(accessToken)

2022-05-31 07:28 UTC, ds-jkreutzfeld commented on integration-tests/src/test/java/net/catenax/irs/smoketest/ItemGraphSmokeTest.java
> +        assertThat(job.getJobState()).isEqualTo(JobState.COMPLETED);
How can you be sure that the job has already completed?

2022-05-31 07:28 UTC, ds-jkreutzfeld commented on integration-tests/src/test/java/net/catenax/irs/smoketest/ItemGraphSmokeTest.java
> +        await().atMost(10, TimeUnit.SECONDS)
10 seconds might actually not be enough, due to slow EDC provider responses.
30 seconds would be better I guess.

2022-05-31 07:28 UTC, ds-jkreutzfeld commented on irs-api/src/main/resources/application.yml
> +    active: ${SPRING_PROFILES_ACTIVE:local}
Why do we need this?

2022-05-31 07:31 UTC, SaberIstos commented on integration-tests/src/test/java/net/catenax/irs/configuration/PropertyConfigurer.java
> +public class PropertyConfigurer {
SmokeTestConfiguration

2022-05-31 14:20 UTC, SaberIstos commented on integration-tests/src/test/java/net/catenax/irs/smoketest/ItemGraphSmokeTest.java
> +        final JobHandle responsePost = given().spec(requestSpecification)
I thought about configuring it once instead of for each get/post call.
Before starting the tests I inject the retrieved token into a RequestSpecBuilder. Additionally I can configure the base URI.

2022-05-31 15:08 UTC, SaberIstos commented on irs-api/src/main/resources/application.yml
> +    active: ${SPRING_PROFILES_ACTIVE:local}
Moved to the application.yml file in the integration-test module.

2022-06-09 12:19 UTC, ds-jhartmann requested changes
You don't have the connection properties for dev. This story is about the Testing of the IRS on DEV-Environment right?

2022-06-09 12:19 UTC, ds-jhartmann commented on integration-tests/src/test/java/net/catenax/irs/smoketest/ItemGraphSmokeIT.java
> +        System.out.println("credentialsProperties.getClientSecret(): " + credentialsProperties.getClientSecret());
Does this print the secret to the console? If so please remove as the console output is accessible publicly on Github.

2022-06-09 12:25 UTC, ds-jhartmann requested changes

2022-06-09 12:25 UTC, ds-jhartmann commented on .github/workflows/CI-Int-Test-Automated.yml
> +          mvn -Dtest=intergartion-tests/src/test/java/net/catenax/irs/smoketest/ItemGraphSmokeTest test \
Also, did you verify that this maven command works? As far as I can see there is no Test Class called ItemGraphSmokeTest

2022-06-09 16:39 UTC, SaberIstos commented on .github/workflows/CI-Int-Test-Automated.yml
> +          distribution: 'adopt'
changed to distribution: 'temurin'

2022-06-09 16:43 UTC, SaberIstos commented on .github/workflows/CI-Int-Test-Automated.yml
> +      - 'feature/TRI-488'
I thought about launching the integration test when a merge into the main branch takes place. Otherwise what is your purpose ? should it just be started manually ?

2022-06-09 16:46 UTC, SaberIstos commented on integration-tests/src/test/java/net/catenax/irs/smoketest/ItemGraphSmokeIT.java
> +        System.out.println("credentialsProperties.getClientSecret(): " + credentialsProperties.getClientSecret());
as you expect just for local test cases. Should not be deployed on the remote branch. Removed.

2022-06-09 16:48 UTC, SaberIstos commented on .github/workflows/CI-Int-Test-Automated.yml
> +          mvn -Dtest=intergartion-tests/src/test/java/net/catenax/irs/smoketest/ItemGraphSmokeTest test \
Right. Didn't push the recent version. The test class should maintain the name ItemGraphSmokeTest.

2022-06-10 11:08 UTC, SaberIstos commented on .github/workflows/CI-Int-Test-Automated.yml
> +      - 'feature/TRI-488'
Removed the push part.

2022-06-10 11:11 UTC, SaberIstos commented on irs-models/src/main/java/net/catenax/irs/component/JobHandle.java
> +@JsonDeserialize(builder = JobHandle.JobHandleBuilder.class)
Deserialization replaced with the annotations 
@Jacksonized
@Builder(toBuilder = true)

and removed @JsonPOJOBuilder(withPrefix = "")

2022-06-10 13:24 UTC, ds-jhartmann requested changes
Please fix the typo and resolve the open comments by Jan.

2022-06-10 13:24 UTC, ds-jhartmann commented on integration-tests/src/test/resources/application.yml
> +erver:
I think there is a typo here "erver"

2022-06-10 13:39 UTC, SaberIstos commented on integration-tests/src/test/resources/application.yml
> +erver:
Corrected to server:
  port: 8080

2022-06-13 09:54 UTC, ds-ext-kmassalski requested changes
- not working with int/dev env's
- missing 'oauth2' in config files

2022-06-13 10:20 UTC, ds-ext-kmassalski requested changes

2022-06-13 10:20 UTC, ds-ext-kmassalski commented on integration-tests/pom.xml
>              <groupId>io.rest-assured</groupId>
Please check one more time, its working fine on my env with:
```
<groupId>io.rest-assured</groupId>
<artifactId>rest-assured</artifactId>
<version>5.1.1</version>
```

2022-06-13 10:20 UTC, ds-ext-kmassalski commented on integration-tests/src/test/java/net/catenax/irs/smoketest/ItemGraphSmokeTest.java
> +        final Jobs responseGet = given().spec(requestSpecification)
Can you use self explanatory names?
Like I have no idea what is a differen between responseGet and responseGetPoll?

2022-06-15 07:48 UTC, SaberIstos commented on integration-tests/src/test/java/net/catenax/irs/smoketest/ItemGraphSmokeTest.java
> +        final Jobs responseGet = given().spec(requestSpecification)
naming optimized to:
private static RequestSpecification authenticationRequest;

final JobHandle createdJobResponse = given().spec(authenticationRequest)

final Jobs getJobByIdResponse = given().spec(authenticationRequest)

final Response pollResponse = given().spec(authenticationRequest)

2022-06-15 10:38 UTC, SaberIstos commented on integration-tests/pom.xml
>              <groupId>io.rest-assured</groupId>
Increased rest-assured version to <version>5.1.1</version>

2022-06-15 10:40 UTC, SaberIstos commented on irs-models/src/main/java/net/catenax/irs/component/enums/BomLifecycle.java
> +@JsonSerialize(using = ToStringSerializer.class)
As shown together the serialization fails when excluding it. Any idea about the cause or how to resolve it ?

2022-06-16 06:07 UTC, ds-ext-kmassalski approved these changes

2022-06-16 06:07 UTC, merged