Tri 380 add owasp dependency check maven plugin & github action
catenax-ng/product-item-relationship-service pull request #119
Opened 2022-05-27 09:24 UTC by ds-agenz

2022-05-31 14:57 UTC, ds-jhartmann requested changes

2022-05-31 14:57 UTC, ds-jhartmann commented on .github/workflows/owasp.yml
> +          distribution: 'adopt'
I would recommend to change the distribution to temurin. https://github.com/actions/setup-java#supported-distributions
I already created a PR to change this for the other workflows.

2022-05-31 14:57 UTC, ds-jhartmann commented on .github/workflows/owasp.yml
> +      security-events: write
The security-events permission is not needed, since you don't add anything to the security issues within this workflow. 
However, you can configure dependency check to output a file in sarif format, which can then be added to the security tab.

2022-06-10 13:11 UTC, ds-jhartmann commented
@ds-ext-kmassalski @ds-ext-ooyeneye can either of you quickly check this PR so we can finish this story?

2022-06-13 09:32 UTC, ds-ext-kmassalski requested changes

2022-06-13 09:45 UTC, ds-jhartmann commented on pom.xml
> +            <id>active</id>
renamed profile to 'dependency-check'

2022-06-13 09:45 UTC, ds-jhartmann commented on .github/workflows/owasp.yml
> +        run: mvn install -Pactive
renamed profile to 'dependency-check'

2022-06-13 10:06 UTC, merged