Feature/tri 370 implement endpoint get a list of jobs with processing state
catenax-ng/product-item-relationship-service pull request #130
Opened 2022-05-31 09:52 UTC by ds-ext-ooyeneye

2022-05-31 10:55 UTC, ds-jkreutzfeld requested changes

2022-05-31 10:55 UTC, ds-jkreutzfeld commented on irs-api/src/test/java/net/catenax/irs/controllers/IrsControllerTest.java
> +                    .andExpect(content().string(containsString(jobId.toString())));
Wouldn't you also want to test for the correct status in the result object?

2022-05-31 10:55 UTC, ds-jkreutzfeld commented on irs-api/src/test/java/net/catenax/irs/IrsApplicationTests.java
> +        assertThat(generatedYaml).isEqualToIgnoringNewLines(fixedYaml);
Why this change? It used to work like this using isEqualToNormalizingNewlines

2022-05-31 10:55 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/net/catenax/irs/dto/JobStatusResult.java
> +@Data
Why not make this immutable with @Value?

2022-05-31 14:30 UTC, ds-ext-ooyeneye commented on irs-api/src/main/java/net/catenax/irs/dto/JobStatusResult.java
> +@Data
Done

2022-05-31 14:31 UTC, ds-ext-ooyeneye commented on irs-api/src/test/java/net/catenax/irs/controllers/IrsControllerTest.java
> +                    .andExpect(content().string(containsString(jobId.toString())));
Done

2022-06-01 06:41 UTC, ds-ext-kmassalski requested changes
```
[Jan Kreutzfeld] added a comment - [17/May/22 2:53]

- Modify response class to contain status as well as the jobId
- Fix default behavior to return jobs of all status instead of none (current behavior)
- Check whether pagination is implementable  (if easily done, then do it)
```
Only first bullet is implemented in the PR. You didnt change default implementation behaviour, what was expected by Martin. Also please leave comment about pagination possibilities.

2022-06-01 06:41 UTC, ds-ext-kmassalski commented on irs-api/src/main/java/net/catenax/irs/services/IrsItemGraphQueryService.java
> +                   .map(x -> JobStatusResult.builder()
Rename x param to sth more sufficient

2022-06-03 10:57 UTC, ds-jkreutzfeld commented on irs-api/src/test/java/net/catenax/irs/IrsApplicationTests.java
> +        assertThat(generatedYaml).isEqualToIgnoringNewLines(fixedYaml);
![image](https://user-images.githubusercontent.com/100288948/171841216-64e33ab6-4358-4804-a951-fbc74d5c09e1.png)
Maybe because you removed the newline at the end :)

2022-06-06 13:20 UTC, ds-ext-kmassalski commented
@ds-ext-ooyeneye please answer or fix review comments!

2022-06-07 06:39 UTC, ds-ext-kmassalski commented
Hi @ds-jhartmann @SaberIstos , can I ask for your opinion here?
Dapo and I had an open discussion this morning, if we should do requested changes for JobStatusResult class or not.

For me changing from String's to specific type properties (UUID, JobStates) gives:
- cleaner solution,
- easier to maintaine and underestand API model, 
- open–closed principle for further modifications/adjustments,
- no need to parse to string few times - spring's json parser does this anyway.

So the question is: what you think - should we stay with String, or do the change?

2022-06-07 07:50 UTC, ds-jhartmann commented
Hi @ds-ext-kmassalski, to understand you correctly: You want to change 'String jobId' to 'UUID jobId' and 'String status' to 'JobState status'? Or do you have something different in mind?

2022-06-07 08:00 UTC, ds-ext-kmassalski commented
"You want to change 'String jobId' to 'UUID jobId' and 'String status' to 'JobState status'?" - correct

2022-06-07 09:32 UTC, ds-jhartmann commented
In this case I think we should do that. As you mentioned, it adds to maintainability, is cleaner to understand and provides precisely what the consumer of our API can expect as a result.

2022-06-07 10:51 UTC, SaberIstos commented
After analyzing the changes in the above feature branch, I guess that using the benefit of the spring json parser is the common way instead of parsing the jobId as a string for several times. So the usage of UUID as a data type is better from my point of view.

2022-06-08 06:18 UTC, ds-ext-ooyeneye commented on irs-api/src/test/java/net/catenax/irs/IrsApplicationTests.java
> +        assertThat(generatedYaml).isEqualToIgnoringNewLines(fixedYaml);
Resolved

2022-06-08 07:05 UTC, ds-ext-kmassalski requested changes
Add test to assert status and bussing logic (findAdd vs findByStates)

2022-06-08 08:54 UTC, ds-ext-kmassalski approved these changes

2022-06-08 08:55 UTC, ds-ext-kmassalski approved these changes

2022-06-08 08:55 UTC, merged