feat(impl):[TRI-517] mapping additional fields
catenax-ng/product-item-relationship-service pull request #158
Opened 2022-06-17 12:29 UTC by ds-ext-kmassalski

2022-06-20 11:47 UTC, ds-jhartmann approved these changes
~~From my POV this looks fine.~~ Can someone else take a look at this as well, please? @ds-jkreutzfeld @ds-ext-ooyeneye @SaberIstos 

Edit: Found issue with quantity in JobResult

2022-06-20 12:39 UTC, ds-jhartmann requested changes

2022-06-21 08:54 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/net/catenax/irs/dto/ChildDataDTO.java
> +                         .build());
Fixed this by correctly using the builder :)

2022-06-21 09:00 UTC, ds-jkreutzfeld approved these changes

2022-06-21 11:43 UTC, ds-jhartmann approved these changes

2022-06-22 07:07 UTC, merged