feature/TRI-385: Remove some unnecessary annotations @ExcludeFromCode…
catenax-ng/product-item-relationship-service pull request #159
Opened 2022-06-21 08:05 UTC by SaberIstos

…CoverageGeneratedReport

2022-06-22 11:05 UTC, ds-jkreutzfeld requested changes
ExcludeFromCodeCoverageGeneratedReport is not used anymore, I guess we can remove it.

2022-06-22 11:05 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/net/catenax/irs/controllers/IrsApiExamplesUtils.java
> +public class IrsApiExamplesUtils {
This class does not seem to be used anywhere. What is its purpose?
It is also the reason why the Sonar build fails.

2022-06-23 08:16 UTC, SaberIstos commented on irs-api/src/main/java/net/catenax/irs/controllers/IrsApiExamplesUtils.java
> +public class IrsApiExamplesUtils {
removed.

2022-06-23 11:06 UTC, ds-jkreutzfeld approved these changes

2022-06-23 11:06 UTC, merged