Fix/tri 522 job attribute last modified on never updated
catenax-ng/product-item-relationship-service pull request #187
Opened 2022-06-30 21:46 UTC by ds-ext-ooyeneye

2022-07-01 11:29 UTC, ds-jkreutzfeld requested changes

2022-07-01 11:29 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/net/catenax/irs/connector/job/MultiTransferJob.java
> +                                                                                                                        ZoneOffset.UTC))
Why do this here if the transition method is called anyway?

2022-07-01 11:29 UTC, ds-jkreutzfeld commented on irs-api/src/test/java/net/catenax/irs/connector/job/PersistentJobStoreTest.java
> -        assertThat(sut.find(otherJobId)).isEmpty();
Why was this removed?

2022-07-01 11:29 UTC, ds-jkreutzfeld commented on irs-api/src/test/java/net/catenax/irs/services/IrsItemGraphQueryServiceSpringBootTest.java
> +        assertThat(lastModifiedOn).isBefore(ZonedDateTime.now());
This assertion doesn't make much sense to me.

Also in none of the tests there is an assertion that the lastModifiedDate has been updated over the lifetime of a job, please add that.

2022-07-01 11:55 UTC, ds-ext-ooyeneye commented on irs-api/src/main/java/net/catenax/irs/connector/job/MultiTransferJob.java
> +                                                                                                                        ZoneOffset.UTC))
Removed

2022-07-06 08:34 UTC, ds-ext-ooyeneye commented on irs-api/src/test/java/net/catenax/irs/connector/job/PersistentJobStoreTest.java
> -        assertThat(sut.find(otherJobId)).isEmpty();
Was done by Jaro

2022-07-06 08:35 UTC, ds-ext-ooyeneye commented on irs-api/src/test/java/net/catenax/irs/services/IrsItemGraphQueryServiceSpringBootTest.java
> +        assertThat(lastModifiedOn).isBefore(ZonedDateTime.now());
Another test rewritten for this test in PersistentJobStoreTest and InMemoryJobTest

2022-07-06 15:00 UTC, ds-jhartmann commented on irs-api/src/test/java/net/catenax/irs/connector/job/PersistentJobStoreTest.java
> -        assertThat(sut.find(otherJobId)).isEmpty();
No it wasn't.

2022-07-07 07:02 UTC, ds-ext-ooyeneye commented on irs-api/src/test/java/net/catenax/irs/connector/job/PersistentJobStoreTest.java
> -        assertThat(sut.find(otherJobId)).isEmpty();
Assertion statement reinstated

2022-07-07 10:01 UTC, ds-jkreutzfeld approved these changes

2022-07-07 10:15 UTC, merged