feat(irs-api):[TRI-509] Add method to retrieve submodel as String and…
catenax-ng/product-item-relationship-service pull request #192
Opened 2022-07-04 15:51 UTC by ds-jhartmann

… API parameter to collect aspects

2022-07-05 13:22 UTC, ds-ext-kmassalski requested changes

2022-07-05 13:22 UTC, ds-ext-kmassalski commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/submodel/domain/SubmodelClient.java
> +    String getSubmodel(String submodelEndpointAddress);
Do we need new method? Previous one was designed to retrieve submodels of any kind, so I think
`SubmodelClient.getSubmodel(address, String.class)` should do the job

2022-07-05 13:22 UTC, ds-ext-kmassalski commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/submodel/domain/SubmodelFacade.java
> +        try {
Double parsing String -> String?
Why not just returning `this.submodelClient.getSubmodel(submodelEndpointAddress);` here?

2022-07-06 06:42 UTC, ds-jhartmann commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/submodel/domain/SubmodelFacade.java
> +        try {
One of the action items of the planning 2 was _"Embed JSON response, but validate it first. If it is not valid JSON, then include it as a String_".
I don't know what the exact reason was anymore and wanted to talk about this, so I left it like that for now.

2022-07-06 06:42 UTC, ds-jhartmann commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/job/AASTransferProcessManager.java
>  import java.nio.charset.StandardCharsets;
I agree. I will try to separate it a bit

2022-07-06 06:42 UTC, ds-jhartmann commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/submodel/domain/SubmodelClient.java
> +    String getSubmodel(String submodelEndpointAddress);
You need to request it like this `SubmodelClient.getSubmodel(address, Object.class)`. However when the response is not in Object/JSON structure, it throws a Exception and we cant retrieve the payload.
For that reason I introduced a new method which just returns the payload as string.

2022-07-06 14:31 UTC, ds-jhartmann commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/job/AASTransferProcessManager.java
> +    private String getAspectType(final SubmodelDescriptor submodelDescriptor) {
Done.

2022-07-06 14:32 UTC, ds-jhartmann commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/submodel/domain/SubmodelFacade.java
> +        try {
As we agreed on, I changed getSubmodelAsString to only return String without parsing.

2022-07-07 13:24 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/submodel/domain/SubmodelClient.java
> +    String getSubmodel(String submodelEndpointAddress);
I think the method overload is fine; otherwise we would have to base the implementation on the type parameter. Keep it simple :)

2022-07-08 06:47 UTC, ds-ext-kmassalski approved these changes

2022-07-08 10:55 UTC, ds-jhartmann commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/job/AASTransferProcessManager.java
> +            final ItemContainer itemContainer = aasHandler.createAndFillItemContainer(jobData, aasTransferProcess, itemId);
Renamed to `collectShellAndSubmodels()` and included JavaDoc for further explanation.

2022-07-08 10:55 UTC, ds-jhartmann commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/submodel/domain/SubmodelFacade.java
> +    public String getSubmodelAsString(final String submodelEndpointAddress) {
Renamed to `getSubmodelRawPayload()`

2022-07-08 10:55 UTC, ds-jhartmann commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/submodel/domain/SubmodelFacade.java
Renamed to `getAssemblyPartRelationshipSubmodel()`

2022-07-08 11:51 UTC, merged