Feature/tri 569 create resource monitoring dashboards
catenax-ng/product-item-relationship-service pull request #210
Opened 2022-07-14 09:27 UTC by ds-ext-ooyeneye

2022-07-14 09:29 UTC, ds-jkreutzfeld commented
I would like to avoid having separate dashboards for every environment. Please find a way to unify this.

2022-07-15 08:12 UTC, ds-jkreutzfeld commented
Please also see the review comments by Martin in the Jira ticket :)

2022-07-19 07:25 UTC, ds-jkreutzfeld approved these changes

2022-07-20 07:01 UTC, ds-jkreutzfeld requested changes
Unfortunately, you broke the yaml files with the formatting.

{{ }} placeholders now look like this: { {  } }

2022-07-20 11:17 UTC, ds-jkreutzfeld approved these changes
Please revert the change in Project.xml, after that is can be merged.

2022-07-20 11:17 UTC, ds-jkreutzfeld commented on .idea/codeStyles/Project.xml
> +    </codeStyleSettings>
As this didn't help, we dont need the change.

2022-07-21 18:10 UTC, ds-ext-ooyeneye commented on .idea/codeStyles/Project.xml
> +    </codeStyleSettings>
Has been reverted

2022-07-25 07:16 UTC, merged