Feature/tri 572 set up job monitoring
catenax-ng/product-item-relationship-service pull request #214
Opened 2022-07-19 11:39 UTC by ds-ext-ooyeneye

2022-07-20 08:50 UTC, ds-jkreutzfeld requested changes

2022-07-26 07:31 UTC, ds-jkreutzfeld requested changes

2022-07-26 07:31 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/net/catenax/irs/services/IrsItemGraphQueryService.java
> +        meterRegistryService.incrementNumberOfCreatedJobs();
The @IRSMetrics at PersistentJobStore#put should already cover this.

2022-07-26 07:31 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/net/catenax/irs/services/IrsItemGraphQueryService.java
> +    @Timed(value = "jobs.processed.complete.time", description = "Amount of time require to process job complete")
This is still an issue.

2022-07-26 07:31 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/net/catenax/irs/connector/job/MultiTransferJob.java
> +            // meterRegistryService.incrementJobFailed();
This can be removed.

2022-07-26 07:31 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/net/catenax/irs/connector/job/JobOrchestrator.java
> +    @IRSMetrics("RUNNING")
The @IRSMetrics at PersistentJobStore#put should already cover this.

2022-07-26 07:31 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/net/catenax/irs/connector/job/IRSMetrics.java
> +            default { };
Is this necessary?

2022-07-26 07:33 UTC, ds-jkreutzfeld commented
Also, please take a look at the code coverage.

2022-07-26 08:36 UTC, ds-ext-ooyeneye commented on irs-api/src/main/java/net/catenax/irs/connector/job/IRSMetrics.java
> +            default { };
This is necessary to provide granular handling of specific metrics that should be collected

2022-07-27 09:50 UTC, ds-ext-ooyeneye commented on irs-api/src/main/java/net/catenax/irs/services/IrsItemGraphQueryService.java
> +            meterRegistryService.incremenException();
New changes make this comment obsolete

2022-07-27 09:50 UTC, ds-ext-ooyeneye commented on irs-api/src/main/java/net/catenax/irs/services/IrsItemGraphQueryService.java
> +    @Timed(value = "jobs.processed.complete.time", description = "Amount of time require to process job complete")
New changes make this comment obsolete

2022-07-28 09:47 UTC, closed without merging