Feature/tri 572 set up job monitoring clean
catenax-ng/product-item-relationship-service pull request #233
Opened 2022-07-28 09:44 UTC by ds-ext-ooyeneye

2022-07-28 11:02 UTC, ds-ext-kmassalski requested changes

2022-07-28 11:02 UTC, ds-ext-kmassalski commented on irs-api/src/main/java/net/catenax/irs/services/MeterRegistryService.java
>      private final Counter counterCreatedJobs;
Why you didnt move `counterCreatedJobs` to `JobMetrics`?
As all other counters are there

2022-07-28 11:16 UTC, ds-ext-ooyeneye commented on irs-api/src/test/java/net/catenax/irs/services/MeterRegistryServiceTest.java
> +        meterRegistryService = TestMother.simpleMeterRegistryService();
Just a shorthand for create MeterRegisterService

2022-07-28 11:16 UTC, ds-ext-ooyeneye commented on irs-api/src/test/java/net/catenax/irs/services/MeterRegistryServiceTest.java
> +    void recordJobStateMetricTest() {
What do you suggest the name should?

2022-07-28 11:17 UTC, ds-ext-ooyeneye commented on irs-api/src/test/java/net/catenax/irs/services/IrsItemGraphQueryServiceSpringBootTest.java
> +    public void checkMetricsRecordingTest() {
Had to be added to satisfy code coverage

2022-07-28 11:18 UTC, ds-ext-ooyeneye commented on irs-api/src/test/java/net/catenax/irs/IrsApplicationTests.java
> +    private MeterRegistryService meterRegistryService;
Is remove

2022-07-28 11:18 UTC, ds-jkreutzfeld requested changes

2022-07-28 11:18 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/net/catenax/irs/services/IrsItemGraphQueryService.java
> +            meterRegistryService.incrementException();
I don't think we should increment this here, as this looks more like a client error.

2022-07-28 11:18 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/net/catenax/irs/services/IrsItemGraphQueryService.java
> +            meterRegistryService.incrementException();
I don't think we should increment this here, as this looks more like a client error.

2022-07-28 11:18 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/net/catenax/irs/services/MeterRegistryService.java
> +                                                      .description("The number exceptions in jobs")
Typo: The number **of** *

2022-07-28 11:18 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/net/catenax/irs/services/MeterRegistryService.java
> +    }
Method is called set, but it actually increments, so why the wrapper?

2022-07-28 11:21 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/net/catenax/irs/connector/job/PersistentJobStore.java
> +    }
With the current logic, you are increasing the total number every time the scheduler ticks.

2022-07-28 11:26 UTC, ds-ext-kmassalski requested changes

2022-07-28 11:26 UTC, ds-ext-kmassalski commented on irs-api/src/main/java/net/catenax/irs/util/JobMetrics.java
> +@Jacksonized
`@Jacksonized` annotation is not needed probably

2022-07-28 11:26 UTC, ds-ext-kmassalski commented on irs-api/src/test/java/net/catenax/irs/services/MeterRegistryServiceTest.java
> +    void recordJobStateMetricTest() {
https://dzone.com/articles/7-popular-unit-test-naming

- *Test postfix in test name is redundand, as its obvious its test
- name of the test should immediately indicate what is being tested inside
- you should fallow given/when/then or Arrange/Act/Assert convention

2022-07-28 13:22 UTC, ds-ext-kmassalski commented on irs-api/src/test/java/net/catenax/irs/services/MeterRegistryServiceTest.java
> +        meterRegistryService = TestMother.simpleMeterRegistryService();
Fixtues/mothers classes should be used to build Pojo/Data objects that can be shared between tests and to increase readability of the tests.

Creation of service is not such case and this is really one liner. Dont think it gives any values to put it inside TestMother.

2022-07-28 15:46 UTC, ds-ext-ooyeneye commented on irs-api/src/main/java/net/catenax/irs/controllers/IrsController.java
> +    @Timed(value = "jobs.processed.register.time", description = "Amount of time require to register a job")
Done

2022-07-28 15:46 UTC, ds-ext-ooyeneye commented on irs-api/src/main/java/net/catenax/irs/controllers/IrsController.java
> +    @Timed(value = "jobs.processed.register.time", description = "Amount of time require to register a job")
Done

2022-07-28 15:46 UTC, ds-ext-ooyeneye commented on irs-api/src/main/java/net/catenax/irs/controllers/IrsController.java
> +    @Timed(value = "jobs.processed.register.time", description = "Amount of time require to register a job")
Done

2022-07-28 15:46 UTC, ds-ext-ooyeneye commented on irs-api/src/main/java/net/catenax/irs/controllers/IrsController.java
> +    @Timed(value = "jobs.processed.cancel.time", description = "Amount of time require to process cancel job")
Done

2022-07-28 15:47 UTC, ds-ext-ooyeneye commented on irs-api/src/main/resources/application.yml
> +        expression: "*/20 * * * * ?"
Done

2022-07-28 15:47 UTC, ds-ext-ooyeneye commented on irs-api/src/main/java/net/catenax/irs/controllers/IrsController.java
> +    @Timed(value = "jobs.processed.getjob.time", description = "Amount of time require to process job complete")
Done

2022-07-28 15:52 UTC, ds-ext-ooyeneye commented on irs-api/src/main/java/net/catenax/irs/services/IrsItemGraphQueryService.java
> +            meterRegistryService.incrementException();
Done

2022-07-28 16:09 UTC, ds-ext-ooyeneye commented on irs-api/src/main/java/net/catenax/irs/services/MeterRegistryService.java
> +                                                      .description("The number exceptions in jobs")
Done

2022-07-28 16:10 UTC, ds-ext-ooyeneye commented on irs-api/src/main/java/net/catenax/irs/services/MeterRegistryService.java
> +    }
Done

2022-07-28 16:21 UTC, ds-ext-ooyeneye commented on irs-api/src/main/java/net/catenax/irs/util/JobMetrics.java
> +@Jacksonized
Done

2022-07-28 16:22 UTC, ds-ext-ooyeneye commented on irs-api/src/test/java/net/catenax/irs/services/IrsItemGraphQueryServiceSpringBootTest.java
> +        final int jobCount = 4;
Done

2022-07-29 07:38 UTC, ds-jkreutzfeld requested changes

2022-07-29 07:38 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/net/catenax/irs/services/MeterRegistryService.java
> +            numbersOfJobsInJobStore.remove(0);
remove(0)?

2022-07-29 07:38 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/net/catenax/irs/services/MeterRegistryService.java
> +            log.info("Incrementing Job in JobStore...");
Misleading log

2022-07-29 07:38 UTC, ds-jkreutzfeld commented on irs-api/src/test/java/net/catenax/irs/services/IrsItemGraphQueryServiceSpringBootTest.java
> +            new MinioContainer.CredentialsProvider(ACCESS_KEY, SECRET_KEY)).withReuse(true);
Why are these necessary now and not before?

2022-07-29 07:58 UTC, ds-ext-ooyeneye commented on irs-api/src/main/java/net/catenax/irs/services/MeterRegistryService.java
> +            numbersOfJobsInJobStore.remove(0);
Fifo, this just to decrease the amount of jobs in the list

2022-07-29 08:09 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/net/catenax/irs/services/MeterRegistryService.java
> +            numbersOfJobsInJobStore.remove(0);
Why use a List at all? You could just use a long and change its value

2022-07-29 08:19 UTC, ds-ext-ooyeneye commented on irs-api/src/test/java/net/catenax/irs/services/IrsItemGraphQueryServiceSpringBootTest.java
> +            new MinioContainer.CredentialsProvider(ACCESS_KEY, SECRET_KEY)).withReuse(true);
Was formally used in the test, but now removed

2022-07-29 08:20 UTC, ds-ext-ooyeneye commented on irs-api/src/main/java/net/catenax/irs/services/MeterRegistryService.java
> +            log.info("Incrementing Job in JobStore...");
Log information changed

2022-07-29 08:24 UTC, ds-ext-ooyeneye commented on irs-api/src/main/java/net/catenax/irs/services/MeterRegistryService.java
> +            numbersOfJobsInJobStore.remove(0);
It's a gauge, we can add or remove, when a job is removed from Jobstore, a counter will not allow this but the gauge does

2022-07-29 08:29 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/net/catenax/irs/services/MeterRegistryService.java
> +            numbersOfJobsInJobStore.remove(0);
The Gauge is fine, I'm talking about the underlying List object, which I don't think is necessary if we just want the total number of jobs anyway.

2022-07-29 11:21 UTC, ds-ext-ooyeneye commented on irs-api/src/main/java/net/catenax/irs/services/MeterRegistryService.java
> +            numbersOfJobsInJobStore.remove(0);
Change from list to Long

2022-08-01 06:59 UTC, ds-ext-ooyeneye commented
A new dashboard is available to be reviewed

2022-08-01 07:22 UTC, ds-ext-ooyeneye commented
A new dashboard is ready

2022-08-04 14:29 UTC, ds-ext-ooyeneye commented
Pull request TRI-573 is now merge to this PR

2022-08-04 19:10 UTC, ds-jkreutzfeld approved these changes

2022-08-08 14:00 UTC, ds-ext-kmassalski requested changes

2022-08-09 08:40 UTC, ds-ext-ooyeneye commented on irs-api/src/main/java/net/catenax/irs/services/MeterRegistryService.java
> +        log.info("Execution time measured for {} is {}", tag, duration);
Done

2022-08-09 08:44 UTC, ds-ext-ooyeneye commented on ci/spotbugs-excludes.xml
> +        <Class name="net.catenax.irs.util.JobMetrics$JobMetricsBuilder"/>
It is needed otherwise the UWF_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR will cause a superfluous error, just like ShellBuilder in the same file

2022-08-09 12:11 UTC, merged