Feature/tri 573 irs api monitoring
catenax-ng/product-item-relationship-service pull request #234
Opened 2022-07-29 06:14 UTC by ds-ext-ooyeneye

2022-07-29 07:54 UTC, ds-jkreutzfeld requested changes

2022-07-29 07:54 UTC, ds-jkreutzfeld commented on chart/grafana/values.yaml
> +  irsmonitoring: resource-monitoring-dashboard.json
Where are the two new dashboards?

2022-07-29 07:57 UTC, ds-jkreutzfeld commented
What is the difference between those panels?
![image](https://user-images.githubusercontent.com/100288948/181712410-396bf13f-4566-4ead-a5b1-c667a38dd0e5.png)

2022-07-29 07:57 UTC, ds-jkreutzfeld commented
And why are there 6 jobs created, but the number of jobs in the Jobstore is 0? Minio has been running for two weeks, so there should be no job reset.

2022-07-29 08:00 UTC, ds-jkreutzfeld commented
Looking at these panels, I have no idea what to read from that.
![image](https://user-images.githubusercontent.com/100288948/181713103-a2656b47-fcdb-4f23-b67a-109f38f1bcf1.png)
Can you explain?

2022-07-29 08:01 UTC, ds-jkreutzfeld commented
What does this panel mean?
![image](https://user-images.githubusercontent.com/100288948/181713267-18ee3919-c17d-4bac-9cfe-ccf29145c4a9.png)

2022-07-29 08:03 UTC, ds-jkreutzfeld commented
Which methods are described here?
![image](https://user-images.githubusercontent.com/100288948/181713570-4c0d7b73-5ce8-431b-927c-61387e5de325.png)

2022-07-29 12:10 UTC, ds-ext-ooyeneye commented on chart/grafana/values.yaml
> +  irsmonitoring: resource-monitoring-dashboard.json
Very strange, they are there in the commit project
![image](https://user-images.githubusercontent.com/100859614/181755579-73b27be7-119b-47b9-b11b-843bb636fd2e.png)

2022-07-29 12:15 UTC, ds-ext-ooyeneye commented
> 

JobStore works find in test, I will need to find out why the JobStore is 0

2022-07-29 13:00 UTC, ds-ext-ooyeneye commented
> And why are there 6 jobs created, but the number of jobs in the Jobstore is 0? Minio has been running for two weeks, so there should be no job reset.

Duplicate one will be remove

2022-08-01 07:00 UTC, ds-ext-ooyeneye commented
A new dashboard is available for review

2022-08-01 07:17 UTC, ds-ext-ooyeneye commented
> Looking at these panels, I have no idea what to read from that. ![image](https://user-images.githubusercontent.com/100288948/181713103-a2656b47-fcdb-4f23-b67a-109f38f1bcf1.png) Can you explain?

The new dashboard can be reviewed

2022-08-01 07:19 UTC, ds-ext-ooyeneye commented
> And why are there 6 jobs created, but the number of jobs in the Jobstore is 0? Minio has been running for two weeks, so there should be no job reset.

The created are counter while job in JobStore is gauge, the counter continue to increase the gauge show the actual content available

2022-08-01 07:21 UTC, ds-ext-ooyeneye commented
> Looking at these panels, I have no idea what to read from that. ![image](https://user-images.githubusercontent.com/100288948/181713103-a2656b47-fcdb-4f23-b67a-109f38f1bcf1.png) Can you explain?

Had been remove, a bit confusing

2022-08-01 07:21 UTC, ds-ext-kmassalski commented
When Job state changes from Running to Completed, running counter is not being decreased.

2022-08-04 14:29 UTC, closed without merging