Update and rename checkov.yml to kics.yml
catenax-ng/product-item-relationship-service pull request #247
Opened 2022-08-05 14:02 UTC by the-tatanka

2022-08-05 14:05 UTC, mkanal requested changes

2022-08-05 14:05 UTC, mkanal commented on .github/workflows/kics.yml
> +  # pull_request:
According to internal team aggreement kics should be executed on each pull request.

2022-08-05 14:05 UTC, mkanal commented on .github/workflows/kics.yml
> +    - cron: "28 15 * * 3"
Why At 15:28 on Wednesday?

2022-08-05 14:05 UTC, mkanal commented on .github/workflows/kics.yml
> +    - cron: "28 15 * * 3"
please add comment when cron is executed.

2022-08-05 21:42 UTC, the-tatanka commented on .github/workflows/kics.yml
> +  # pull_request:
Done

2022-08-05 21:44 UTC, the-tatanka commented on .github/workflows/kics.yml
> +    - cron: "28 15 * * 3"
Oh no, my mistake.
Thanks for the hint.

2022-08-08 11:46 UTC, mkanal approved these changes

2022-08-08 11:46 UTC, merged