fix(irs-api):[TRI-631] Added method to find and delete cancelled jobs
catenax-ng/product-item-relationship-service pull request #254
Opened 2022-08-10 08:02 UTC by ds-ext-ooyeneye

2022-08-10 08:41 UTC, ds-ext-kmassalski commented
The bug was completely different, and has nothing to do with canceled jobs.
Please read one more time bug/task description.

2022-08-10 08:41 UTC, ds-ext-kmassalski requested changes
The bug was completely different, and has nothing to do with canceled jobs.
Please read one more time bug/task description.

2022-08-11 08:46 UTC, ds-ext-kmassalski requested changes

2022-08-11 08:46 UTC, ds-ext-kmassalski commented on irs-api/src/main/java/net/catenax/irs/connector/job/JobOrchestrator.java
> +    public void findAndCleanupCancelledJobs() {
Currently there is no requirement that we should remove canceled jobs, additionaly it was not in scope of this task.
So please remove this scheduler method.

2022-08-11 08:46 UTC, ds-ext-kmassalski commented on irs-api/src/main/java/net/catenax/irs/persistence/MinioBlobPersistence.java
> +    private void deleteRelatedJobsByProcessId(final List<String> processIds) throws BlobPersistenceException {
deleteRelatedJobsByProcessId - is not the best name, as inside this function we are not 'deleting jobs', but rather items/processes.
Please change to more suitable:
deleteRelatedWithJobItems or deleteRelatedWithJobProcesses

2022-08-11 08:46 UTC, ds-ext-kmassalski commented on irs-api/src/test/java/net/catenax/irs/persistence/MinioBlobPersistenceTest.java
> +        testee.putBlob(processIds.get(0), "testContent".getBytes(StandardCharsets.UTF_8));
I suppose you wanted: processIds.get(1) here

2022-08-11 08:48 UTC, ds-ext-ooyeneye commented on irs-api/src/main/java/net/catenax/irs/connector/job/JobOrchestrator.java
> +    public void findAndCleanupCancelledJobs() {
But can be eventually needed

2022-08-11 08:57 UTC, ds-ext-ooyeneye commented on irs-api/src/main/java/net/catenax/irs/persistence/MinioBlobPersistence.java
> +    private void deleteRelatedJobsByProcessId(final List<String> processIds) throws BlobPersistenceException {
But you are still using Job within the method name, maybe a rather befitting name could be deleteRelatedBlobs

2022-08-12 12:00 UTC, ds-ext-kmassalski requested changes

2022-08-12 12:00 UTC, ds-ext-kmassalski commented on irs-api/src/test/java/net/catenax/irs/connector/job/PersistentJobStoreTest.java
> +        final int sizeAfterCreation = blobStoreSpy.findBlobByPrefix("job:").size();
Expected test casse:
- register job that will be completed
- count items in blob store - ~10 items
- delete/remove process
- count items in blob store - 0 items

2022-08-16 06:56 UTC, ds-ext-ooyeneye commented
An extended item search from the bucket was done after deleting the job item from the bucket, using the job id,  complete transfer id, and process id. Should no item be gotten from this search and eventually there are still items related to the job in the bucket, then we dealing with Item gone woe, (i.e. a wild Item), the bug is then beyond IRS.

2022-08-16 08:05 UTC, ds-ext-ooyeneye commented on irs-api/src/test/java/net/catenax/irs/connector/job/PersistentJobStoreTest.java
> +        final int sizeAfterCreation = blobStoreSpy.findBlobByPrefix("job:").size();
The above test was 0 but does not solve the problem of related item been found in the bucket

2022-08-16 13:56 UTC, ds-jhartmann approved these changes

2022-08-17 07:07 UTC, ds-ext-kmassalski approved these changes

2022-08-17 07:07 UTC, merged