feat(irs-api):[TRI-API] Adding helm chart for ESR Spike
catenax-ng/product-item-relationship-service pull request #257
Opened 2022-08-16 08:29 UTC by ds-ext-ooyeneye

2022-08-16 10:02 UTC, ds-jhartmann requested changes

2022-08-16 10:02 UTC, ds-jhartmann commented on chart/aaswrapper/values-esr.yaml
> +        - "irs-aas-wrapper-esr.int.demo.catena-x.net"
Why is the url on int cluster here? Insn't it supposed to be on dev?

2022-08-16 10:02 UTC, ds-jhartmann commented on chart/edc-consumer-controlplane/values-esr.yaml
> +        - "irs-consumer-controlplane-esr.int.demo.catena-x.net"
Why is the url on int cluster here? Insn't it supposed to be on dev?

2022-08-16 10:02 UTC, ds-jhartmann commented on chart/irs/values-esr.yaml
> +        - "irs-esr.int.demo.catena-x.net"
Why is the url on int cluster here? Insn't it supposed to be on dev?

2022-08-16 10:06 UTC, ds-ext-kmassalski requested changes
Missing components. There are more things to deploy, not only aaswrapper, edc controlplane, dataplane and irs.

Besides of that mixed configuration, sometimes there is DEV, sometimes INT.

2022-08-16 10:06 UTC, ds-ext-kmassalski commented on chart/edc-consumer-controlplane/values-esr.yaml
> +    - host: "irs-consumer-controlplane-esr.int.demo.catena-x.net"
We agreed to deploy on DEV

2022-08-16 10:06 UTC, ds-ext-kmassalski commented on chart/irs/values-esr.yaml
> +    - host: "irs-esr.int.demo.catena-x.net"
We agreed to deploy on DEV

2022-08-18 11:35 UTC, ds-ext-ooyeneye commented on chart/edc-consumer-controlplane/values-esr.yaml
> +        - "irs-consumer-controlplane-esr.int.demo.catena-x.net"
Done

2022-08-18 13:09 UTC, ds-jhartmann requested changes

2022-08-18 13:09 UTC, ds-jhartmann commented on chart/edc-consumer-dataplane/values-esr.yaml
> +    edc.vault.tenantid=495463c3-0991-4659-9cc5-94b4a3f7b1d6
Azure vault is no longer available. You need to use the hashicorp vault images

2022-08-18 13:09 UTC, ds-jhartmann commented on chart/edc-consumer-controlplane/values-esr.yaml
> +    edc.vault.tenantid=495463c3-0991-4659-9cc5-94b4a3f7b1d6
Azure vault is no longer available. You need to use the hashicorp vault images

2022-08-19 07:35 UTC, ds-ext-kmassalski requested changes
Not passing acceptence criteria - read task description and comment from Sprint planning 2 one more time.
Not deployed entire env, missing postman collection, different naming then agreed in task.

2022-08-23 08:24 UTC, ds-ext-ooyeneye commented on chart/edc-consumer-controlplane/values-esr.yaml
> +    edc.vault.tenantid=495463c3-0991-4659-9cc5-94b4a3f7b1d6
Had been change to hashicorp vault

2022-08-23 08:24 UTC, ds-ext-ooyeneye commented on chart/irs/values-esr.yaml
> +  submodel:
Adapted

2022-08-29 16:38 UTC, ds-ext-ooyeneye commented
Please see TRI-666 for continual reviewing of this branch, issue mentioned here had been resolved in TRI-666

2022-08-30 08:15 UTC, ds-jkreutzfeld commented
Is this binary file needed? [chart/edc-postgresql/charts/common-1.16.1.tgz](https://github.com/catenax-ng/product-item-relationship-service/pull/257/files#diff-7b306faf6e96e16b43e7e1f69a4ec26239bdc62b2a56e99e9836991f9eddd730)

2022-08-30 08:16 UTC, ds-jkreutzfeld approved these changes

2022-08-30 15:45 UTC, merged