[Tri 414] network of network
catenax-ng/product-item-relationship-service pull request #287
Opened 2022-08-31 17:12 UTC by mkanal

2022-09-01 06:23 UTC, jzbmw requested changes

2022-09-01 06:23 UTC, jzbmw commented on uml-diagrams/spike/esr-certificates/esr-certificate-sequence-traverse_childs.puml
> +ESRSubServer <-- IRS : 200
One line below

2022-09-01 06:23 UTC, jzbmw commented on uml-diagrams/spike/esr-certificates/esr-certificate-sequence-traverse_childs.puml
> +loop 100 times
why a 100 times? This loop is a loop until the result of the job is completed, correct. More like a polling

2022-09-01 06:23 UTC, jzbmw commented on uml-diagrams/spike/esr-certificates/esr-certificate-sequence-traverse_childs.puml
> +ESRSubServer <--  OnSupplyAPI : ISO14001 Response
SupplyOn

2022-09-01 06:23 UTC, jzbmw commented on uml-diagrams/spike/esr-certificates/esr-certificate-state-machine.puml
> +
Isnt the approval as of Monday out of scope?

2022-09-06 05:20 UTC, mkanal commented on uml-diagrams/spike/esr-certificates/esr-certificate-sequence-traverse_childs.puml
> +loop 100 times
Should have a predefined end. Endless looping willl cause in a job which could never gibve a result. 100 might a good number.

2022-09-08 08:11 UTC, mkanal commented
@jzbmw Issues are fixed. Please review.

2022-09-13 11:49 UTC, bubbur86 approved these changes
#``

2022-09-17 06:17 UTC, bubbur86 reviewed
#331

2022-09-19 05:58 UTC, jzbmw approved these changes

2022-09-22 08:55 UTC, ds-jkreutzfeld commented
@mkanal what is the state of this PR?

2022-10-06 09:56 UTC, merged