feat(api):[TRI-339] introduce depth in recursive processing
catenax-ng/product-item-relationship-service pull request #33
Opened 2022-04-21 17:34 UTC by ds-ext-kmassalski

Its a Draft as Im still working on proper unit tests, but please take a look if this makes sense,
Also I need feedback if there is a need to also serialize depth in AASTransferProcessDeserializer?

2022-04-21 17:39 UTC, ds-ext-kmassalski commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/job/AASTransferProcess.java
> +            return new AASTransferProcess(idValue, null);
Need feedback what to do here

2022-04-25 14:21 UTC, ds-jkreutzfeld requested changes

2022-04-25 14:21 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/net/catenax/irs/controllers/IrsController.java
> +                    value = "jobStates", required = false, defaultValue = "") final List<JobState> jobStates) {
Why the empty default?

2022-04-25 14:21 UTC, ds-jkreutzfeld commented on irs-api/src/test/java/net/catenax/irs/services/IrsItemGraphQueryServiceTest.java
> +    @Disabled // its not consistent before TRI-390 not resolved
Put a note into TRI-390 to enable this test again after the fix :)

2022-04-25 14:21 UTC, ds-jkreutzfeld commented on irs-api/src/test/java/net/catenax/irs/controllers/IrsControllerTest.java
> +import org.testcontainers.shaded.com.fasterxml.jackson.databind.ObjectMapper;
Usage of shaded object mapper - you might want to use the real dependency here

2022-04-25 14:21 UTC, ds-jkreutzfeld commented on irs-api/src/test/java/net/catenax/irs/services/IrsItemGraphQueryServiceTest.java
> +    @Disabled // its not consistent before TRI-390 not resolved
Put a note into TRI-390 to enable this test again after the fix :)

2022-04-26 09:26 UTC, ds-jkreutzfeld approved these changes

2022-04-26 09:26 UTC, merged