Feature/tri 318 fault tolerant irs job processing
catenax-ng/product-item-relationship-service pull request #34
Opened 2022-04-22 07:29 UTC by ds-jhartmann

https://jira.catena-x.net/browse/TRI-318
I've noticed that I have a typo in the jira ticket number of the commit messages. Please ignore that the correct ticket number is TRI-318.

2022-04-25 14:09 UTC, ds-ext-kmassalski requested changes
Please check comments :)

2022-04-25 14:09 UTC, ds-ext-kmassalski commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/submodel/domain/SubmodelClient.java
> +        try {
Dont think its necessary to introduce try - catch block here.
Rest template will simply throw some **WebException, you can catch it in Facade and build tombstone there.
Additionaly: you should separate business logic from infrastructure or IO (rest, db, controllers etc)

2022-04-25 14:09 UTC, ds-ext-kmassalski commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/submodel/domain/SubmodelClientException.java
> +public class SubmodelClientException extends Exception {
Redundand to me - catch RestClientException in facade instead.

2022-04-26 07:39 UTC, ds-jhartmann commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/submodel/domain/ChildData.java
> +    private LocalDateTime assembledOn;
According to our test data, the field is called assembledOn

2022-04-26 07:39 UTC, ds-jhartmann commented on irs-api/src/test/java/net/catenax/irs/aaswrapper/DeserializationTest.java
> +class DeserializationTest {
You are right. I used this Test to verify that our models are correctly serialized and deserialized but it is no longer necessary.

2022-04-26 07:41 UTC, ds-jhartmann commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/submodel/domain/SubmodelClientException.java
> +public class SubmodelClientException extends Exception {
I introduced this checked exception because the RestClientException is unchecked. Futhermore the response gets converted to the Aspect whithin the restTemplate.getForEntity. This does not allow us to retrieve further information from the response, e.g. 404 not found.
Should the method return the ResponseEntity instead?

2022-04-26 17:21 UTC, ds-ext-kmassalski requested changes
Adjust to new design

2022-04-28 13:59 UTC, ds-ext-kmassalski requested changes
Last three minor changes and I think we can merge

2022-04-28 13:59 UTC, ds-ext-kmassalski commented on irs-models/src/main/java/net/catenax/irs/component/ProcessingError.java
> +    private final String exception;
Remove as we discussed - no need to return technical details to clients

2022-04-28 13:59 UTC, ds-ext-kmassalski commented on irs-api/src/test/java/net/catenax/irs/aaswrapper/registry/domain/DigitalTwinRegistryFacadeTest.java
> +    void shouldThrowExceptionWhenRequestError() {
Add some enters, so its easier to read and underestand :) given-when-then aproach

2022-04-28 13:59 UTC, ds-ext-kmassalski commented on irs-api/src/main/java/net/catenax/irs/dto/SubmodelType.java
> +    private final String value;
@allargsconstructor + @getter should do the job

2022-04-28 17:09 UTC, ds-ext-kmassalski approved these changes

2022-04-28 17:09 UTC, merged