Fix/fix esr certificate semantic
catenax-ng/product-item-relationship-service pull request #360
Opened 2022-09-28 12:47 UTC by ds-jhartmann

Enabled deserialization of certifiacte object
Added EsrCertificate to IRS request
Increased polling rate to every 2s 30 times

2022-09-28 15:02 UTC, ds-ext-kmassalski requested changes

2022-09-28 15:02 UTC, ds-ext-kmassalski commented on irs-api/src/main/resources/application.yml
> +        waitDuration: 2s
Retry every 2s seems to be to fast :)

2022-09-29 06:29 UTC, ds-jhartmann commented on irs-api/src/main/resources/application.yml
> +        waitDuration: 2s
Maybe for the first 10 or 15 seconds, but after the IRS job is finished, we want to get the result as fast as possible so we don't run into the 3 minute gateway timeout of DEV

2022-09-29 06:30 UTC, ds-jhartmann commented on esr/src/main/java/org/eclipse/tractusx/esr/irs/model/shell/Shell.java
> +                .filter(assetId -> "manufacturerId".equals(assetId.getKey()))
Do you have a documentation for this? I tried to find something in regards to that but didn't so I just copied it from SerialPartTypization and Batch

2022-09-30 10:25 UTC, ds-ext-kmassalski commented on irs-api/src/main/resources/application.yml
> +        waitDuration: 2s
Ok

2022-09-30 12:27 UTC, ds-ext-kmassalski approved these changes

2022-09-30 12:31 UTC, merged