Feature/tri 403
catenax-ng/product-item-relationship-service pull request #46
Opened 2022-04-29 06:47 UTC by SaberIstos

2022-04-29 07:56 UTC, ds-jkreutzfeld requested changes

2022-04-29 08:00 UTC, SaberIstos commented on irs-api/src/main/java/net/catenax/irs/connector/job/TransferProcessManager.java
> +            Consumer<P> transferProcessCompleted, String lifecyleContext);
I agree

2022-04-29 08:07 UTC, SaberIstos commented on irs-api/src/main/java/net/catenax/irs/services/IrsItemGraphQueryService.java
> +        if (bomLifecyclesFromAASWrapper.contains(bomLifecycleFormRequest)) {
I wondered about this point in the task description: Remark: As the /submodel endpoint does not support filters, we have first to consume the model to check if the bomLifecycle matches or not.

I understood from it that I should check if the given BomLifecyle is available as a submodel on the aaswrapper server side ?

2022-04-29 08:12 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/net/catenax/irs/services/IrsItemGraphQueryService.java
> +        if (bomLifecyclesFromAASWrapper.contains(bomLifecycleFormRequest)) {
This means that we cannot add the filter parameters to the submodel call, as they don't support filtering.
So we need to read the submodel and then filter the data, as you have (partly) done in AASTransferProcessManager#102.
But all of the filtering must happen there in the transfer process, not in the register job method. The transfer process is executed asynchronously.

2022-04-29 08:15 UTC, SaberIstos commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/job/AASTransferProcessManager.java
> +                                                  .filter(child -> child.getLifecycleContext().equals(lifecyleContext))
do you mean something like this:
        final List<String> childIds = relationship.getChildParts()
                                                  .stream()
                                                  .map(child -> {
                                                      if (child.getLifecycleContext().equals(lifecyleContext)) {
                                                          return child.getChildCatenaXId();
                                                      }
                                                      return null;
                                                  })
                                                  .collect(Collectors.toList());

2022-04-29 09:39 UTC, SaberIstos commented on irs-api/src/test/java/net/catenax/irs/connector/job/JobOrchestratorTest.java
> +        verify(processManager, never()).initiateRequest(eq(dataRequest2), any(), any(), eq("AsBuilt"));
final AssemblyPartRelationshipDTO filteredDto = AssemblyPartRelationshipDTO.builder()
                                                                                   .catenaXId(relationship.getCatenaXId())
                                                                                   .childParts(filteredChildData)
                                                                                   .build();

        itemContainer.assemblyPartRelationship(filteredDto);

2022-04-29 09:41 UTC, SaberIstos commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/job/AASTransferProcessManager.java
> +                                                  .filter(child -> child.getLifecycleContext().equals(lifecyleContext))
final AssemblyPartRelationshipDTO filteredDto = AssemblyPartRelationshipDTO.builder()
                                                                                   .catenaXId(relationship.getCatenaXId())
                                                                                   .childParts(filteredChildData)
                                                                                   .build();

        itemContainer.assemblyPartRelationship(filteredDto);

2022-04-29 09:48 UTC, SaberIstos commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/job/AASTransferProcessManager.java
> +                                                  .filter(child -> child.getLifecycleContext().equals(lifecyleContext))
already done. I just inserted a part of the code. But thx.

2022-04-29 09:51 UTC, SaberIstos commented on irs-api/src/test/java/net/catenax/irs/connector/job/JobOrchestratorTest.java
> +        verify(processManager, never()).initiateRequest(eq(dataRequest2), any(), any(), eq("AsBuilt"));
private static final String BOMLIFECYCLE = "AsBuilt";

2022-04-29 11:52 UTC, ds-jkreutzfeld requested changes

2022-04-29 11:52 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/net/catenax/irs/services/IrsItemGraphQueryService.java
> +        if (bomLifecycleFormRequest != null) {
What if the BomLifecycle is null? Then no job is started right now.
When no BomLifecycle is passed to the IRS Controller by the caller, then we will just not filter that but retrieve all data.

2022-04-29 11:52 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/net/catenax/irs/services/IrsItemGraphQueryService.java
> +        if (bomLifecycleFormRequest != null) {
So, if the bomLifecycle is present, add it to the param map, otherwise not.

2022-04-29 11:52 UTC, ds-jkreutzfeld commented on irs-api/src/test/java/net/catenax/irs/IrsFunctionalTest.java
> +        assertThat(finishedJob.get().getRelationships()).isEmpty();
This seems wrong, why the change?

2022-04-29 11:52 UTC, ds-jkreutzfeld commented on irs-api/src/test/java/net/catenax/irs/controllers/IrsControllerTest.java
> +    @Disabled
Why disable this?

2022-04-29 11:58 UTC, ds-jkreutzfeld commented
Please check the merge conflicts :)

2022-04-29 14:33 UTC, SaberIstos commented on irs-api/src/main/java/net/catenax/irs/services/IrsItemGraphQueryService.java
> +        if (bomLifecycleFormRequest != null) {
the distinguition between with or without BomLifecyle should as well be handled in the AASTransferProcessManager

2022-04-29 15:11 UTC, SaberIstos commented on irs-api/src/test/java/net/catenax/irs/controllers/IrsControllerTest.java
> +    @Disabled
removed

2022-04-29 15:12 UTC, SaberIstos commented on irs-api/src/test/java/net/catenax/irs/IrsFunctionalTest.java
> +        assertThat(finishedJob.get().getRelationships()).isEmpty();
restored.

2022-04-29 15:19 UTC, SaberIstos commented on irs-api/src/test/java/net/catenax/irs/services/IrsItemGraphQueryServiceTest.java
> +                           .build();
@Test
    void cancelJobById() {
        final Job job = generate.fakeJob(JobState.CANCELED);

        final MultiTransferJob multiTransferJob = MultiTransferJob.builder().job(job).build();

        when(jobStore.cancelJob(jobId.toString())).thenReturn(Optional.ofNullable(multiTransferJob));
        final Job canceledJob = testee.cancelJobById(jobId);

        assertNotNull(canceledJob);
        assertEquals(canceledJob.getJobState().name(), JobState.CANCELED.name());
    }

2022-04-29 18:48 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/job/AASTransferProcessManager.java
> +                                                                                                       .equals(lifecyleContext))
Swap this equals to avoid nullpointers

2022-04-29 18:48 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/job/AASTransferProcessManager.java
> +                           .collect(Collectors.toList());
just reuse the already filtered list and map it to IDs

2022-04-29 18:48 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/net/catenax/irs/services/IrsItemGraphQueryService.java
> +    private Map buildJobParams(final @NonNull RegisterJob request) {
Missing generics for the Map

2022-04-29 18:51 UTC, ds-jkreutzfeld approved these changes

2022-04-29 18:55 UTC, ds-jkreutzfeld commented
Implementation wise, this is ready to be merged from my point of view.
However, I don't see a test for the filter mechanism.
@ds-jhartmann or @ds-ext-kmassalski - if you have the chance to add this on monday, that would be great, as Saber and myself are on vacation.
If not, then feel free to merge this anyway and Saber needs to create a test as soon as he comes back. ;)

2022-05-01 13:24 UTC, merged

2022-05-01 13:56 UTC, SaberIstos commented on irs-api/src/main/java/net/catenax/irs/services/IrsItemGraphQueryService.java
> +    private Map buildJobParams(final @NonNull RegisterJob request) {
private Map<String, String> buildJobParams(final @NonNull RegisterJob request) {

2022-05-01 13:58 UTC, SaberIstos commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/job/AASTransferProcessManager.java
> +                                                                                                       .equals(lifecyleContext))
.filter(childDataDTO -> StringUtils.equals(childDataDTO.getLifecycleContext(), lifecyleContext))