fix(veracode):[TRI-397] Add Veracode integration
catenax-ng/product-item-relationship-service pull request #50
Opened 2022-04-29 11:44 UTC by mkanal

2022-05-19 06:58 UTC, ds-jhartmann requested changes
I requested two changes, the rest looks good to me.

2022-05-19 06:58 UTC, ds-jhartmann commented on .github/workflows/VeraCode.yml
> +          distribution: 'corretto'
In the workflow CI-main we use distribution 'adopt'. Might want to use this here too.

2022-05-19 06:58 UTC, ds-jhartmann commented on .github/workflows/VeraCode.yml
> +      - name: Set up Maven
Re-use the action from our CI-main workflow 'Cache maven packages'

2022-05-20 10:04 UTC, ds-agenz commented on .github/workflows/VeraCode.yml
> +          distribution: 'corretto'
thanks., i changed it

2022-05-20 10:04 UTC, ds-agenz commented on .github/workflows/VeraCode.yml
> +      - name: Set up Maven
I added the caching

2022-05-20 10:19 UTC, ds-jhartmann approved these changes

2022-05-23 10:21 UTC, merged