Feature/tri 306 orchestration asynchronous calls over irs api
catenax-ng/product-item-relationship-service pull request #58
Opened 2022-05-03 08:50 UTC by ds-ext-ooyeneye

Asynchronous Job Orchestration

2022-05-03 09:16 UTC, ds-ext-kmassalski commented
You should fix the problem with code-formatter as soon as possible. Right now we need to review multiple files, instead only few with real changes.

2022-05-03 09:26 UTC, ds-ext-kmassalski requested changes

2022-05-03 09:26 UTC, ds-ext-kmassalski commented on irs-api/pom.xml
> +            <version>2.6.5</version>
This is managed by parent pom, but why are u changing this anyway?

2022-05-03 09:26 UTC, ds-ext-kmassalski commented on irs-models/src/main/java/net/catenax/irs/dtos/ItemsTreeView.java
> -@ExcludeFromCodeCoverageGeneratedReport
Why are u removing this annotation from model classes?

2022-05-03 09:26 UTC, ds-ext-kmassalski commented on irs-models/src/main/java/net/catenax/irs/component/Summary.java
> -@ExcludeFromCodeCoverageGeneratedReport
Why are u removing this annotation from model classes?

2022-05-03 09:26 UTC, ds-ext-kmassalski commented on irs-models/src/main/java/net/catenax/irs/component/RegisterJob.java
> -@ExcludeFromCodeCoverageGeneratedReport
Why are u removing this annotation from model classes?

2022-05-03 09:26 UTC, ds-ext-kmassalski commented on irs-models/src/main/java/net/catenax/irs/component/Endpoint.java
> -@ExcludeFromCodeCoverageGeneratedReport
Why are u removing this annotation from model classes?

2022-05-03 09:26 UTC, ds-ext-kmassalski commented on irs-common/pom.xml.rej
> +diff a/irs-common/pom.xml b/irs-common/pom.xml	(rejected hunks)
What is the purpose of the file?

2022-05-03 09:26 UTC, ds-ext-kmassalski commented on irs-api/src/test/java/net/catenax/irs/exceptions/EntityCancelExceptionTest.java
> +    public void cancelExceptionTest() {
You shouldnt test mockito library, rather ours application business logic :)

2022-05-03 09:26 UTC, ds-ext-kmassalski commented on irs-api/src/main/java/net/catenax/irs/exceptions/EntityCancelException.java
> + * General entity not found exception.
Wrong description.

2022-05-03 09:26 UTC, ds-ext-kmassalski commented on irs-api/src/main/java/net/catenax/irs/services/AsyncJobHandlerService.java
> +                            Thread.currentThread().wait(WAIT_TIME);
This seems to be potentialy a bad design. Please describe what you want to achieve here.

2022-05-03 13:23 UTC, ds-jhartmann requested changes

2022-05-03 13:23 UTC, ds-jhartmann commented on irs-models/src/main/java/net/catenax/irs/component/Job.java
> +    @Override
You might want to replace this with a @ToString annotation

2022-05-03 13:23 UTC, ds-jhartmann commented on irs-models/src/main/java/net/catenax/irs/component/IrsPartRelationshipsWithInfos.java
> +public class IrsPartRelationshipsWithInfos {
I think we removed this Class previously. I think it is not used anywhere.

2022-05-03 13:23 UTC, ds-jhartmann commented on irs-api/src/test/java/net/catenax/irs/services/JobHandlerTest.java
> +        JobInitiateResponse errorResponse = JobInitiateResponse.builder()
This variable is never used

2022-05-03 13:23 UTC, ds-jhartmann commented on irs-api/src/test/java/net/catenax/irs/services/JobHandlerTest.java
> +// @TestPropertySource(locations = "classpath:asynctest.yaml")
Please remove the commented code completely

2022-05-03 13:23 UTC, ds-jhartmann commented on irs-api/src/test/java/net/catenax/irs/config/AsyncConfigTest.java
> +public class AsyncConfigTest {
I don't think you use this class in your tests. If you don't remove it, you might want to consider a rename, since this is not a test class, but a config class.

2022-05-03 13:23 UTC, ds-jhartmann commented on irs-api/src/main/java/net/catenax/irs/services/AsyncJobHandlerService.java
> +    public CompletableFuture<Jobs> getCompleteJobResult(final UUID jobId)
Sonar marks this as a Code Smell because of high complexity. Please refactor to make it easier to understand

2022-05-03 21:11 UTC, ds-ext-ooyeneye commented on irs-models/src/main/java/net/catenax/irs/component/Summary.java
> -@ExcludeFromCodeCoverageGeneratedReport
The model classes had been already excluded from coverage report in the parent pom. See the parent pom from line 142 to 145

2022-05-03 21:11 UTC, ds-ext-ooyeneye commented on irs-models/src/main/java/net/catenax/irs/dtos/ItemsTreeView.java
> -@ExcludeFromCodeCoverageGeneratedReport
The model classes had been already excluded from coverage report in the parent pom. See the parent pom from line 142 to 145

2022-05-03 21:11 UTC, ds-ext-ooyeneye commented on irs-models/src/main/java/net/catenax/irs/component/Endpoint.java
> -@ExcludeFromCodeCoverageGeneratedReport
The model classes had been already excluded from coverage report in the parent pom. See the parent pom from line 142 to 145

2022-05-03 21:13 UTC, ds-ext-ooyeneye commented on irs-common/pom.xml.rej
> +diff a/irs-common/pom.xml b/irs-common/pom.xml	(rejected hunks)
Common pom had always been there.

2022-05-03 21:16 UTC, ds-ext-ooyeneye commented on irs-api/src/test/java/net/catenax/irs/exceptions/EntityCancelExceptionTest.java
> +    public void cancelExceptionTest() {
Sorry, I don't get this comment. The test is just to increase the coverage for the package

2022-05-03 21:23 UTC, ds-ext-ooyeneye commented on irs-api/src/main/java/net/catenax/irs/services/AsyncJobHandlerService.java
> +                            Thread.currentThread().wait(WAIT_TIME);
It's had already been removed

2022-05-03 21:26 UTC, ds-ext-ooyeneye commented on irs-api/src/main/java/net/catenax/irs/exceptions/EntityCancelException.java
> + * General entity not found exception.
Description had been changed

2022-05-03 21:28 UTC, ds-ext-ooyeneye commented on irs-models/src/main/java/net/catenax/irs/component/RegisterJob.java
> -@ExcludeFromCodeCoverageGeneratedReport
The model classes had been already excluded from coverage report in the parent pom. See the parent pom from line 142 to 145

2022-05-04 09:38 UTC, ds-ext-ooyeneye commented on irs-api/src/main/java/net/catenax/irs/services/AsyncJobHandlerService.java
> +                            Thread.currentThread().wait(WAIT_TIME);
Done

2022-05-04 09:49 UTC, ds-ext-ooyeneye commented on irs-api/src/test/java/net/catenax/irs/config/AsyncConfigTest.java
> +public class AsyncConfigTest {
Resolved

2022-05-04 10:13 UTC, ds-ext-ooyeneye commented on irs-api/src/test/java/net/catenax/irs/services/JobHandlerTest.java
> +// @TestPropertySource(locations = "classpath:asynctest.yaml")
Done

2022-05-04 10:14 UTC, ds-ext-ooyeneye commented on irs-api/src/test/java/net/catenax/irs/services/JobHandlerTest.java
> +        JobInitiateResponse errorResponse = JobInitiateResponse.builder()
Removed

2022-05-04 10:35 UTC, ds-ext-ooyeneye commented on irs-models/src/main/java/net/catenax/irs/component/IrsPartRelationshipsWithInfos.java
> +public class IrsPartRelationshipsWithInfos {
Removed

2022-05-04 11:52 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/net/catenax/irs/services/AsyncJobHandlerService.java
> +public class AsyncJobHandlerService implements IAsyncJobHandlerService {
I don't get which problem this class is trying to solve. Can you please explain?

2022-05-04 12:15 UTC, ds-ext-ooyeneye commented on irs-api/src/main/java/net/catenax/irs/services/AsyncJobHandlerService.java
> +public class AsyncJobHandlerService implements IAsyncJobHandlerService {
The last should solve an asynchronous job orchestration request. It should fetch either partially or complete job using IrsItemGraphQueryService. It continuously try to fetch a complete or partial job until it successfully or timeout. There are still some todo like when to timeout.

2022-05-05 08:16 UTC, ds-jkreutzfeld approved these changes

2022-05-05 08:23 UTC, merged