Feature/tri 437
catenax-ng/product-item-relationship-service pull request #70
Opened 2022-05-08 19:12 UTC by SaberIstos

2022-05-10 10:32 UTC, ds-jhartmann requested changes
Do you use the right code formatter? The formatter was applied to the whole main branch last friday, so formatting should not change. Please configure IntelliJ to use the formatter stored in this project and push the formatted code.

2022-05-10 10:32 UTC, ds-jhartmann commented on irs-api/src/test/java/net/catenax/irs/connector/job/MultiTransferJobTest.java
> +import java.util.List;
unused import

2022-05-10 10:32 UTC, ds-jhartmann commented on irs-api/src/test/java/net/catenax/irs/connector/job/MultiTransferJobTest.java
> +import net.catenax.irs.component.enums.AspectType;
unused import

2022-05-10 10:32 UTC, ds-jhartmann commented on irs-api/src/test/java/net/catenax/irs/util/TestMother.java
> +    public JobDataDTO jobDataDTO() {
you can make this static like the other methods in this class

2022-05-10 10:32 UTC, ds-jhartmann commented on irs-api/src/test/java/net/catenax/irs/util/TestMother.java
> +    public JobDataDTO jobDataFilter() {
you can make this static like the other methods in this class

2022-05-10 10:32 UTC, ds-jhartmann commented on irs-parent/pom.xml
> +        <org.apache.commons.version>4.4</org.apache.commons.version>
You really shouldn't add a new dependency just for a notEmpty function.

2022-05-10 10:32 UTC, ds-jhartmann commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/submodel/domain/SubmodelFacade.java
> +    private boolean shouldFilterByLifecycleContext(final String lifecyleContext) {
typo: lifecycleContext

2022-05-10 10:32 UTC, ds-jhartmann commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/submodel/domain/SubmodelFacade.java
> +        return StringUtils.isNotBlank(lifecyleContext);
typo: lifecycleContext

2022-05-10 10:32 UTC, ds-jhartmann commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/registry/domain/DigitalTwinRegistryFacade.java
> +        return isNotEmpty(aspectTypes);
You can replace this imported method with your own.

2022-05-10 14:46 UTC, SaberIstos commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/job/AASRecursiveJobHandler.java
> +        log.info("Starting recursive request for job {}", job.getJob().getJobId().toString());
log.info("Initiating request for job {}", job.getJobIdString());

2022-05-10 15:16 UTC, SaberIstos commented on irs-api/src/main/java/net/catenax/irs/dto/JobDataDTO.java
> +public class JobDataDTO {
/**
 * JobParameter model used for job creation
 */
@Data
@Builder(toBuilder = true)
@JsonDeserialize(builder = JobParameter.JobParameterBuilder.class)
public class JobParameter {




    /**
     * Builder class
     */
    @JsonPOJOBuilder(withPrefix = "")
    public static class JobParameterBuilder {
    }

2022-05-10 15:20 UTC, SaberIstos commented on irs-api/src/main/java/net/catenax/irs/connector/job/MultiTransferJob.java
> +/*    @Singular("jobDatum")*/
/**
     * Arbitrary data attached to the job.
     */
    @Getter
    private JobParameter jobData;

2022-05-10 15:23 UTC, SaberIstos commented on irs-api/src/test/java/net/catenax/irs/aaswrapper/job/AASTransferProcessManagerTest.java
> +public class AASTransferProcessManagerTest {
@ExtendWith(MockitoExtension.class)
class AASTransferProcessManagerTest {

2022-05-10 15:24 UTC, SaberIstos commented on irs-api/src/test/java/net/catenax/irs/connector/job/MultiTransferJobTest.java
> +import net.catenax.irs.component.enums.AspectType;
package net.catenax.irs.connector.job;

import static org.assertj.core.api.Assertions.assertThatExceptionOfType;

import com.github.javafaker.Faker;
import net.catenax.irs.dto.JobParameter;
import net.catenax.irs.util.TestMother;
import org.junit.jupiter.api.Test;

class MultiTransferJobTest {

2022-05-10 16:48 UTC, SaberIstos commented on irs-api/src/test/java/net/catenax/irs/util/TestMother.java
> +    public JobDataDTO jobDataFilter() {
public static JobParameter jobParameter() {
        return JobParameter.builder()
                           .rootItemId("urn:uuid:8a61c8db-561e-4db0-84ec-a693fc5ffdf6")
                           .treeDepthId("")
                           .bomLifecycle("AsBuilt")
                           .aspectTypes(List.of(AspectType.SERIAL_PART_TYPIZATION.toString().toLowerCase(Locale.ROOT),
                                 AspectType.ASSEMBLY_PART_RELATIONSHIP.toString().toLowerCase(Locale.ROOT)))
                           .build();
    }

    public static JobParameter jobParameterFilter() {
        return JobParameter.builder()
                           .rootItemId("urn:uuid:8a61c8db-561e-4db0-84ec-a693fc5ffdf6")
                           .treeDepthId("")
                           .bomLifecycle("AsRequired")
                           .aspectTypes(List.of(AspectType.MATERIAL_ASPECT.toString().toLowerCase(Locale.ROOT)))
                           .build();
    }

2022-05-10 16:53 UTC, SaberIstos commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/submodel/domain/SubmodelFacade.java
> +    private boolean shouldFilterByLifecycleContext(final String lifecyleContext) {
private boolean shouldFilterByLifecycleContext(final String lifecycleContext) {
        return StringUtils.isNotBlank(lifecycleContext);
    }

2022-05-10 16:54 UTC, SaberIstos commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/submodel/domain/SubmodelFacade.java
> +        return StringUtils.isNotBlank(lifecyleContext);
private boolean shouldFilterByLifecycleContext(final String lifecycleContext) {
        return StringUtils.isNotBlank(lifecycleContext);
    }

2022-05-10 17:01 UTC, SaberIstos commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/registry/domain/DigitalTwinRegistryFacade.java
> +        return isNotEmpty(aspectTypes);
private boolean shouldFilterByAspectType(final List<String> aspectTypes) {
        return aspectTypes != null && aspectTypes.size() > 0;
    }

2022-05-11 09:06 UTC, ds-jkreutzfeld requested changes

2022-05-11 10:10 UTC, SaberIstos commented on .idea/codeStyles/codeStyleConfig.xml
> -    <option name="USE_PER_PROJECT_SETTINGS" value="true" />
Updated with the main branche state:
<component name="ProjectCodeStyleConfiguration">
  <state>
    <option name="USE_PER_PROJECT_SETTINGS" value="true" />
  </state>
</component>

2022-05-11 10:17 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/net/catenax/irs/dto/JobParameter.java
> +    private String treeDepth;
Also, why is this a string? :D

2022-05-11 10:32 UTC, SaberIstos commented on irs-api/src/main/java/net/catenax/irs/dto/JobParameter.java
> +    private String treeDepth;
In the previous main code, we're using a Map<String, String> where we convert to String:
paramMap.put(DEPTH_ID_KEY, String.valueOf(request.getDepth()));

I didn't change to Integer.

Do you see any side effect setting directly to private Integer treeDepth; ?

2022-05-11 10:38 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/net/catenax/irs/dto/JobParameter.java
> +    private String treeDepth;
The map was pretty generic, so String was just the common denominator.

As we defined the depth to always be > 0 and <= 100, I think "int" should be fine (don't need null here with "Integer").

2022-05-11 10:54 UTC, SaberIstos commented on irs-api/src/main/java/net/catenax/irs/dto/JobParameter.java
> +    private String treeDepth;
/**
     * Expected depth of the tree
     */
    private int treeDepth;

2022-05-11 18:27 UTC, ds-jkreutzfeld approved these changes

2022-05-11 18:27 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/net/catenax/irs/aaswrapper/job/AASRecursiveJobHandler.java
> +        return jobData.getTreeDepth();
Don't know if this method is really necessary now anymore.

2022-05-12 06:38 UTC, merged